version: "3.7"
services:
  mysql_db:
    image: "mysql:5.6"
    restart: always

    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  api_service:
     build: .
     restart: always
     ports:
      - 8050:8050
     depends_on:
      - mysql_db
     links:
      - mysql_db:app_db
#  # needed in order to work properly on Windows:
#  # https://stackoverflow.com/questions/54911021/unable-to-start-docker-mongo-image-on-windows
#  volumes:
#    mongodata: